### ISSUE TITLE
There's a test that says "Change this test to true when your app is working"

### ISSUE THREAD

**Issue by psan2** [learn-co-curriculum/react-using-callbacks-to-pass-information-lab#3]
I'm not sure this is a valid test strategy - it would make more sense to use the built-in Learn.co buttons for lab completion when there are no tests (e.g., instead of including that as a test, stick to the 'Completed' button on Learn.co)

**Comment by pmhofmann** [comment]
I second this, it feels very unfinished to run the tests only to see the sole test state to change the test file to `expect(true).to.equal(true)`

Additionally the working example gif doesn't display when looking at the lab in browser

**Comment by maxwellbenton** [comment]
Hi @psan2,

Thank you for providing this feedback. We've updated this lesson to be a full code-along and removed this test so that Learn no longer requires passing tests for this lesson, which should resolve this issue.

Thank you for contributing!
